(set-face-attribute 'term-bold nil :weight 'unspecified)

(set-face-attribute 'term-color-black nil :foreground "#ABB2BF" :background 'unspecified)
(set-face-attribute 'term-color-blue nil :foreground "#61AFEF" :background 'unspecified)
(set-face-attribute 'term-color-cyan nil :foreground "#56B6C2" :background 'unspecified)
(set-face-attribute 'term-color-green nil :foreground "#98C379" :background 'unspecified)
(set-face-attribute 'term-color-magenta nil :foreground "#C678DD" :background 'unspecified)
(set-face-attribute 'term-color-red nil :foreground "#E06C75" :background 'unspecified)
(set-face-attribute 'term-color-white nil :foreground "#ABB2BF" :background 'unspecified)
(set-face-attribute 'term-color-yellow nil :foreground "#D19A66" :background 'unspecified)
