(set-face-attribute 'font-lock-type-face nil :foreground "#D19A66")
(set-face-attribute 'font-lock-builtin-face nil :foreground "#56B6C2")
(set-face-attribute 'font-lock-comment-face nil :foreground "#5C6370")
(set-face-attribute 'font-lock-constant-face nil :foreground "#56B6C2")
(set-face-attribute 'font-lock-function-name-face nil :foreground "#61AFEF")
(set-face-attribute 'font-lock-keyword-face nil :foreground "#C678DD")
(set-face-attribute 'font-lock-string-face nil :foreground "#98C379")
(set-face-attribute 'font-lock-variable-name-face nil :foreground "#E06C75")
